import math
x1 = int(input())
y1 = int(input())
x2 = int(input())
y2 = int(input())
x3 = int(input())
y3 = int(input())
x4 = int(input())
y4 = int(input())
A = math.sqrt(math.pow((x2-x1),2)+math.pow((y2-y1),2))
B = math.sqrt(math.pow((x3-x2),2)+math.pow((y3-y2),2))
C = math.sqrt(math.pow((x4-x3),2)+math.pow((y4-y3),2))
D = math.sqrt(math.pow((x1-x4),2)+math.pow((y1-y4),2))
print("Периметр=", A+B+C+D)
